name: flutter_components
description: Predesigned Flutter components used by the Daryeel2 schema renderer.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^4.0.0
  geolocator: ^13.0.0
  flutter_runtime:
    path: ../flutter_runtime
  flutter_schema_renderer:
    path: ../flutter_schema_renderer

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.2.2

flutter: