REQUEST_CREATED = "request_created"
REQUEST_STATUS_CHANGED = "request_status_changed"
CUSTOMER_CONFIRMATION_REQUESTED = "customer_confirmation_requested"
CUSTOMER_CONFIRMATION_RESOLVED = "customer_confirmation_resolved"
ASSIGNMENT_CREATED = "assignment_created"
ASSIGNMENT_CLOSED = "assignment_closed"
ATTACHMENT_ADDED = "attachment_added"
ATTACHMENT_REMOVED = "attachment_removed"
PAYMENT_RECORDED = "payment_recorded"
FULFILLMENT_STARTED = "fulfillment_started"
FULFILLMENT_COMPLETED = "fulfillment_completed"

REQUEST_EVENT_TYPES = {
    REQUEST_CREATED,
    REQUEST_STATUS_CHANGED,
    CUSTOMER_CONFIRMATION_REQUESTED,
    CUSTOMER_CONFIRMATION_RESOLVED,
    ASSIGNMENT_CREATED,
    ASSIGNMENT_CLOSED,
    ATTACHMENT_ADDED,
    ATTACHMENT_REMOVED,
    PAYMENT_RECORDED,
    FULFILLMENT_STARTED,
    FULFILLMENT_COMPLETED,
}
